---
title: "CyTOF Titration Concentration Scorer"
author: "Michael de Kok"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: TRUE
    theme: united
    css: style.css
    version: 1.3
params:
  PREGATING_CHANNELS:
    label: "If the following markers exist, assign them to Pregating Channels and do not plot/score them. Seperated by spaces."
    value: "Ce140Di Ir191Di Ir193Di Rh103Di Pd102Di Pd104Di Pd105Di Pd108Di Pd110Di Xe131Di Ce133Di Ba138Di BCKG190Di"
    input: text
  INSTRUMENT_CHANNELS:
    label: "If the following channels exist, assign them to Instrument Channels and do not plot/score them. Sperated by spaces."
    value: "Time Event_length Center SampleID Offset Width Residual FileNum"
    input: text
  PREGATES:
    label: "Perform the following pregates (with format 'channel{<or>}threshold'). Seperated by spaces."
    value: "" #Ce140Di<250 Ir191Di>200 Ir191Di<450 Y89Di>10
    input: text
  SPILLOVER:
    label: "Perform the following actions regarding Spillover:"
    value: "Use Spillovers for Scoring"
    choices: ["Do Nothing", "Use Spillovers for Scoring", "Use Spillovers for Scoring & Compensate Data in Graphs"]
    input: select
  SPILLOVERMATRIX:
    label: "If previous is not 'Do Nothing', use the following Spillover Matrix file."
    value: "../Supplemental Data/Spillover_Fluidigm.xlsx"
    input: file
  ARCSINH: 
    label: "Perform ArcSinh transformation on data."
    value: TRUE
    input: checkbox
  ARCSINHCOFAC: 
    label: "Cofactor to use during ArcSinh transformation."
    value: 5
    input: numeric 
  VIOLINPLOT: 
    label: "Use a Violin instead of Density Plot for Single Marker Titration Plots"
    value: FALSE
    input: checkbox     
  DENSITYSQUARES: 
    label: "Amount of squares for Density plot. 50-150 recommended. Higher = more detail, but more memory required."
    value: 150
    input: numeric 
  SCORES:
    label: "Names of score types, seperated by commas.*"
    value: "Intensity Score,AOF Score,Concentration Score,Overall / Weighted Score"
    input: text
  K: 
    label: "Size of local neighborhood used for Area Overlap Frequency (AOF) calculation."
    value: 30
    input: numeric    
---

Adapted from http://biosurf.wiki/#!/wiki/cytof, Nowicka et al. (2019), Amir et al. (2018), and the unpublished work of Jan Verhoeff

# 1. Loading of Packages

```{r packages, echo = TRUE, results='hide', message=FALSE}

## Check if all necessary packages are installed by trying to load each
PACKAGES_TOTAL <- c('abind', 'askpass', 'assertthat', 'backports', 'base64enc', 'beachmat', 'beeswarm', 'BH', 'Biobase', 'BiocGenerics', 'BiocInstaller', 'BiocNeighbors', 'BiocParallel', 'BiocSingular', 'bitops', 'brew', 'callr', 'car', 'carData', 'CATALYST', 'caTools', 'cellranger', 'circlize', 'cli', 'clipr', 'clisymbols', 'clue', 'colorspace', 'colourpicker', 'colorRamps', 'commonmark', 'ComplexHeatmap', 'ConsensusClusterPlus', 'corpcor', 'covr', 'crayon', 'crosstalk', 'curl', 'cydar', 'cytofCore', 'cytofkit', 'cytolib', 'cytutils', 'data.table', 'DelayedArray', 'DelayedMatrixStats', 'DEoptimR', 'desc', 'destiny', 'devtools', 'digest', 'doParallel', 'dotCall64', 'dplyr', 'drc', 'DT', 'e1071', 'edgeR', 'ellipsis', 'evaluate', 'fansi', 'fastmap', 'fields', 'flowCL', 'flowCore', 'flowDensity', 'FlowSOM', 'flowUtils', 'flowViz', 'flowWorkspace', 'forcats', 'foreach', 'formatR', 'fs', 'futile.logger', 'futile.options', 'gdata', 'GenomeInfoDb', 'GenomeInfoDbData', 'GenomicRanges', 'GEOmap', 'GetoptLong', 'ggbeeswarm', 'ggplot2', 'ggrepel', 'ggridges', 'ggthemes', 'gh', 'git2r', 'GlobalOptions', 'glue', 'gplots', 'graph', 'gridBase', 'gridExtra', 'gtable', 'gtools', 'haven', 'HDF5Array', 'hexbin', 'highr', 'hms', 'htmltools', 'htmlwidgets', 'httpuv', 'httr', 'IDPmisc', 'igraph', 'ini', 'installr', 'IRanges', 'irlba', 'iterators', 'jsonlite', 'knitr', 'kableExtra', 'kohonen', 'labeling', 'laeken', 'lambda.r', 'later', 'latticeExtra', 'lazyeval', 'lifecycle', 'limma', 'lme4', 'lmtest', 'locfit', 'magrittr', 'maps', 'maptools', 'markdown', 'MASS', 'MatrixModels', 'matrixStats', 'MBA', 'MEM', 'memoise', 'mime', 'miniUI', 'minqa', 'miscTools', 'multcomp', 'munsell', 'mvtnorm', 'ncdfFlow', 'nloptr', 'nnls', 'openssl', 'openxlsx', 'pbkrtest', 'pcaPP', 'pdist', 'permute', 'pheatmap', 'pillar', 'pkgbuild', 'pkgconfig', 'pkgload', 'plogr', 'plotly', 'plotrix', 'plyr', 'png', 'praise', 'prettyunits', 'processx', 'progress', 'promises', 'proxy', 'ps', 'purrr', 'quantreg', 'R6', 'Radviz', 'ranger', 'RANN', 'RBGL', 'rcmdcheck', 'RColorBrewer', 'Rcpp', 'RcppAnnoy', 'RcppArmadillo', 'RcppEigen', 'RcppHNSW', 'RcppParallel', 'RCurl', 'readr', 'readxl', 'rematch', 'remotes', 'reshape2', 'rex', 'RFOC', 'rgeos', 'Rgraphviz', 'rhdf5', 'Rhdf5lib', 'rio', 'rjson', 'rlang', 'rmarkdown', 'robustbase', 'roxygen2', 'Rphenograph', 'RPMG', 'rprojroot', 'RProtoBufLib', 'rrcov', 'RSEIS', 'rstudioapi', 'rsvd', 'Rtsne', 'RUnit', 'rversions', 'Rwave', 'S4Vectors', 'sandwich', 'scales', 'scater', 'scatterplot3d', 'sessioninfo', 'shape', 'shiny', 'shinyBS', 'shinydashboard', 'shinyFiles', 'shinyjs', 'SingleCellExperiment', 'smoother', 'snow', 'sourcetools', 'sp', 'spam', 'SPARQL', 'SparseM', 'splancs', 'statmod', 'stringi', 'stringr', 'SummarizedExperiment', 'sys', 'testthat', 'TH.data', 'tibble', 'tidyr', 'tidyselect', 'tinytex', 'tsne', 'TTR', 'usethis', 'utf8', 'vcd', 'vctrs', 'vegan', 'VGAM', 'VIM', 'vipor', 'viridis', 'viridisLite', 'whisker', 'withr', 'xfun', 'XML', 'xml2', 'xopen', 'xtable', 'xts', 'XVector', 'yaml', 'zeallot', 'zip', 'zlibbioc', 'zoo')

installation_needed <- unlist(lapply(PACKAGES_TOTAL, require, character.only = TRUE, quietly = TRUE))
installation_needed <- PACKAGES_TOTAL[installation_needed == FALSE]

## Stop if not all required packages are installed
if(length(installation_needed) > 0) {stop(paste("\n\nNot all necessary packages are installed! Run the Installation Executable or contact the author. The following packages are missing:", paste(installation_needed, collapse = ", ")))}

## Set behaviour of functions using randomness to the same version, so results are the same regardless of R version
RNGversion("3.5.3")

```

# 2. Data Importing

```{r import, message = FALSE}

## Load and print used parameters for future reference
load(file = "../temp.RData")
message("Input Files: ", files)
message("Output Directory: ", outputdir)
print(paste("Input Files: ", files))
print(paste("Output Directory: ", outputdir))
print("User Defined Parameters: ")
params

## Unzip Zipped files
#zip_files <- list.files(pattern='.zip$', full=TRUE, ignore.case = TRUE)
#if (!isEmpty(zip_files)) {unzip(zipfile = zip_files)}
#fcs_files <- list.files(pattern='.fcs$', full=TRUE, ignore.case = TRUE)

## Concatenate if needed, load the FCS File and print its summary
if (!concat) {fcs <- read.FCS(filename = files, transformation = FALSE)} else {fcs <- concatFCS(x = files, file_num = TRUE)
write.FCS(fcs, filename = paste(outputdir,".fcs",sep=""))}
exprs <- as.data.frame(fcs@exprs)

## Check is Sample column is present, otherwise stop
if (is.null(exprs$FileNum)) {stop("This Single File was not concatenated using this Script! Please re-concatenate your file using this script.")}
samplenumber <- length(unique(exprs$FileNum))

## Save current data as "uncompensated" in case compensation occurs and comparisons are needed
fcs_uncompensated <- fcs
exprs_uncompensated <- exprs

## Display 
fcs@parameters@data
t(summary(exprs))

```

# 3. Data Preprocessing

```{r preprocessing}

## Spillover Correction using Spillover Matrix 
if (params$SPILLOVER != "Do Nothing") {
  #spillovermatrix <- spillover(x = fcs, )
  spillovermatrix <- readxl::read_xlsx(path = params$SPILLOVERMATRIX)
  spillovermatrix <- tibble::column_to_rownames(spillovermatrix, colnames(spillovermatrix)[1])
  compensationmatrix <- spillovermatrix[rownames(spillovermatrix) %in% colnames(fcs@exprs), colnames(spillovermatrix) %in% colnames(fcs@exprs)]
  
  spillovermarkers <- character()
  for (spillovermarker in rownames(compensationmatrix)) {
    if ((sum(!is.na(compensationmatrix[spillovermarker])) + sum(!is.na(compensationmatrix[,spillovermarker]))) > 2) 
      {spillovermarkers <- c(spillovermarkers,spillovermarker)}}
  
    if (params$SPILLOVER == "Give Warnings & Compensate Data") {
    fcs_compensated <- compensate(x = fcs, spillover = compensationmatrix)
    fcs <- fcs_compensated
    exprs_compensated <- as.data.frame(fcs_compensated@exprs)
    exprs <- exprs_compensated
    t(summary(exprs_compensated))
  }
}

## Data Pre-Gating
pregating <- function(x, pregate) {
  message(paste("Applying Pregate", pregate));
  if (grepl("<", pregate, fixed=TRUE)) {filterargs <- strsplit(pregate, split = "<")[[1]]; exprs2 <- exprs[exprs[filterargs[1]] < as.numeric(filterargs[2]),]};
  if (grepl(">", pregate, fixed=TRUE)) {filterargs <- strsplit(pregate, split = ">")[[1]]; exprs2 <- exprs[exprs[filterargs[1]] > as.numeric(filterargs[2]),]};
  num_removed <- dim(x)[1] - dim(exprs2)[1] 
  print(paste("Pregate", pregate, "applied succesfully.", num_removed, "cells have been filtered out.")) 
  return(exprs2) }

pregates <- strsplit(params$PREGATES, split = " ")[[1]] 
for (pregate in pregates) {exprs <- pregating(exprs, pregate)}

## Channel Description
pregating_channels <- strsplit(params$PREGATING_CHANNELS, split = " ")[[1]]
pregating_channels <- pregating_channels[pregating_channels %in% colnames(exprs)]
instrument_channels <- strsplit(params$INSTRUMENT_CHANNELS, split = " ")[[1]]
instrument_channels <- instrument_channels[instrument_channels %in% colnames(exprs)]
lineage_channels <- unlist(colnames(exprs))[!unlist(colnames(exprs)) %in% c(pregating_channels,instrument_channels)]

## Combine Metal and Marker names to make it human readable, using information in the parameter data slot
metalmarkers <- list()
markers <- gsub(pattern = ".*_", replacement = "", x = as.vector(fcs@parameters@data$desc));
for (markerid in which(!is.na(markers))) {metalmarkers[[colnames(exprs)[markerid]]] <- markers[markerid]}

## Bead Normalization: Already performed by software before data import
## Compensation:       Already performed by software before data import
## Debarcoding:        Already performed by software before data import

## Arcsinh Data Transformation
message(paste("Arcsinh Data Transformation enabled:",params$ARCSINH)); if (params$ARCSINH) {
  require(MASS)
  require(RColorBrewer)
  k <- 11; my.cols <- rev(brewer.pal(k, "RdYlBu"))
  cofac <- params$ARCSINHCOFAC
  #plot(exprs[,c("CD8", "CD4")], pch=".", col="grey", main="CD8 vs CD4")
  #z <- kde2d(exprs[,"CD8"], h = length(exprs[,"CD8"]), exprs[,"CD4"], n=50)
  #contour(z, drawlabels=FALSE, nlevels=k, col=my.cols, add=TRUE)
  exprs <- cbind(asinh(exprs[,c(pregating_channels, lineage_channels)]/cofac), exprs[,instrument_channels])
  #plot(exprs[,c("CD8", "CD4")], pch=".", col="grey", main="CD8 vs CD4 (transformed counts)")
  #z <- kde2d(exprs[,"CD8"], h = length(exprs[,"CD8"]), exprs[,"CD4"], n=50)
  #contour(z, drawlabels=FALSE, nlevels=k, col=my.cols, add=TRUE)
  t(summary(exprs))
}


## TODO: Batch Effects ?!?!

```

# 4. Clustering for AOF Scoring

```{r clustering, echo = TRUE, results='hold', message=FALSE}

## Cluster Data and calculate AOF for each sample
AOFScores <- list()
exprs_spread <- list()
exprs$Sample <- NA
for (sample in 1:samplenumber) {
  message(paste("\nClustering Sample",sample,"out of", samplenumber))
  sampledata <- dplyr::filter(exprs, exprs$FileNum == sample)
  Rphenograph_out <- Rphenograph::Rphenograph(sampledata[,lineage_channels], k = params$K)
  AOF <- greedyCytometryAof(fcs_data = sampledata[,lineage_channels], y = Rphenograph_out[[2]]$membership)
  AOFScores[[sample]] <- column_to_rownames(.data = AOF, var = "ChannelName")
   
  ## Artificially spread data on x-axis instead of single value per sample
  sampledata <- dplyr::select(sampledata, -starts_with("Sample"))
  sampledata$Sample <- rnorm(n = length(sampledata$FileNum), mean = sample, sd = 0.1)
  exprs_spread[[sample]] <- sampledata
  }

exprs_spread <- rbind.fill(exprs_spread)

```

# 5. Analysing & Scoring

```{r scoring, warning = FALSE, results = "asis"}

## Set up Scoring Tables & Lists
scoretypes <- strsplit(params$SCORES, split = ",")[[1]] 
nr  <- samplenumber
nc  <- length(scoretypes)
ndf <- length(lineage_channels)
scores <- setNames(replicate(ndf,setNames(as.data.frame(matrix(nrow = nr, ncol = nc)),scoretypes),simplify=FALSE),lineage_channels)
bestsamples <- list()

## Plot Functions
plotviolinplot <- function(x, y) {
  dat <- data.frame(x = unname(x), y = unname(y))
  dat <- dat[dat[2] > 0 ,]
<<<<<<< HEAD
  return(ggplot(dat, aes(x, y, fill = x)) + 
           geom_violin(show.legend = TRUE) + 
           ylim(0, quantile(exprs[,marker], 0.9995))  + 
           scale_x_discrete(breaks = seq(1:samplenumber)) + 
           labs(title = paste(marker, "-", metalmarkers[[marker]]), x = "Concentration", y = "Expression") + 
           theme(text = element_text(size=20), axis.text.x = element_text(size=20, hjust=1), axis.text.y = element_text(size=20, hjust=1)) + 
           geom_rect(xmin = bestsamples[[marker]]-0.5, ymin =-0.10, xmax = bestsamples[[marker]]+0.5, ymax = quantile(exprs[,marker], 0.9994), color = "red", fill = NA) +
           scale_fill_manual(values = rev(colorRampPalette(colors = RColorBrewer::brewer.pal(name = "Blues", n = 9))(length(unique(dat$x))))) + 
           theme_classic() + 
           geom_boxplot(width=0.1, outlier.size = 0, outlier.stroke = 0))}
=======
  return(ggplot(dat) + geom_violin(aes(x, y, fill = x), show.legend = TRUE) + ylim(0, quantile(exprs[,marker], 0.9995))  + scale_x_discrete(breaks = seq(1:samplenumber)) + labs(title = paste(marker, "-", metalmarkers[[marker]]), x = "Concentration", y = "Expression") + theme(text = element_text(size=20), axis.text.x = element_text(size=20, hjust=1), axis.text.y = element_text(size=20, hjust=1)) + geom_rect(xmin = bestsamples[[marker]]-0.5, ymin =-0.10, xmax = bestsamples[[marker]]+0.5, ymax = quantile(exprs[,marker], 0.9994), color = "red", fill = NA) + scale_fill_brewer(direction = -1, palette="Blues") + theme_classic())} # + geom_boxplot(width=0.1) 
>>>>>>> eb6a6a4d6835886af27d79d4c842f42c10259c3d

plotdensityplot <- function(x, y) {
  dat <- data.frame(x = unname(x), y = unname(y))
  dat <- dat[dat[2] > 0 ,]
<<<<<<< HEAD
  return(ggplot(dat, aes(x, y, fill = ..density..)) + 
           geom_bin2d(bins = 100, show.legend = TRUE) + 
           scale_fill_gradientn(colours = colorRamps::matlab.like2(100)) + 
           ylim(0, quantile(exprs[,marker], 0.9995))  + 
           labs(title = paste(marker, "-", metalmarkers[[marker]]), x = "Concentration", y = "Expression") + 
           theme(text = element_text(size=20), axis.text.x = element_text(size=20, hjust=1), axis.text.y = element_text(size=20, hjust=1)) + 
           geom_rect(xmin = bestsamples[[marker]]-0.5, ymin = 0, xmax = bestsamples[[marker]]+0.5, ymax = quantile(exprs[,marker], 0.9994), color = "red", fill = NA) + 
           scale_x_continuous(breaks = seq(1:samplenumber)))}
=======
  return(ggplot(dat) + geom_bin2d(aes(x, y, fill = ..density..), bins = 100, show.legend = TRUE) + scale_fill_gradientn(colours = colorRamps::matlab.like2(100)) + ylim(0, quantile(exprs[,marker], 0.9995))  + labs(title = paste(marker, "-", metalmarkers[[marker]]), x = "Concentration", y = "Expression") + theme(text = element_text(size=20), axis.text.x = element_text(size=20, hjust=1), axis.text.y = element_text(size=20, hjust=1)) + geom_rect(xmin = bestsamples[[marker]]-0.5, ymin = 0, xmax = bestsamples[[marker]]+0.5, ymax = quantile(exprs[,marker], 0.9994), color = "red", fill = NA) + scale_x_continuous(breaks = seq(1:samplenumber)))}
>>>>>>> eb6a6a4d6835886af27d79d4c842f42c10259c3d

## Base Scoring Loop, Scoring each Marker Per Titration
densityplots <- list()
for (marker in lineage_channels) {
  maxexpression <- quantile(exprs[,marker], 0.98)
  scores$marker <- as.data.frame(scores$marker)
  for (sample in 1:samplenumber) {
    sampledata <- dplyr::filter(exprs, exprs$FileNum == sample)[,marker]
    scores[[marker]][sample,scoretypes[1]] <- round((quantile(as.numeric(sampledata), 0.98)) / maxexpression, 2)
    #scores[[marker]][sample,scoretypes[2]] <- round(log((1-AOFScores[[sample]][marker,"Aof"])*100,10)/2,2)
    scores[[marker]][sample,scoretypes[2]] <- round(1-AOFScores[[sample]][marker,"Aof"],2)
    scores[[marker]][sample,scoretypes[3]] <- round(sqrt(sample / 10), 2)
  }
<<<<<<< HEAD
  
=======

>>>>>>> eb6a6a4d6835886af27d79d4c842f42c10259c3d
  ## Corrections for Intensity Scores
  scores[[marker]][,scoretypes[1]] <- round(scores[[marker]][,scoretypes[1]] / (max(scores[[marker]][,scoretypes[1]])),2)
  scores[[marker]][scores[[marker]] == "NaN"] <- 0
  
  ## Determine Optimal Samples per Marker
  scores[[marker]][,scoretypes[4]] <- round(rowMeans(scores[[marker]][,1:3]),2) 
  bestsamples[[marker]] <- as.numeric(rownames(scores[[marker]])[which.max(scores[[marker]]$`Overall / Weighted Score`)])
  
  ## Generate Density Plot for Marker
  if (params$VIOLINPLOT) {densityplots[[marker]] <- plotviolinplot(x = as.factor(exprs$FileNum), y = exprs[marker])}
  else {densityplots[[marker]] <- plotdensityplot(x = exprs_spread["Sample"], y = exprs_spread[marker])}
}

```

<<<<<<< HEAD
# 6. Generating Tables & Plots
=======

>>>>>>> eb6a6a4d6835886af27d79d4c842f42c10259c3d

```{r output, warning = FALSE, message = FALSE, results = "asis"}
## Set up Output Folder
if (!(dir.exists(file.path(outputdir, "Markers")))) {dir.create(file.path(outputdir, "Markers"))}
setwd(paste(outputdir,"Markers", sep = "\\"))

## Prepare Spillover Variables and Function
spilloversummaries <- list()
spilloverplots <- list()
finalspilloverplots <- list()
spillovermatrix <- compensationmatrix
spillovermatrix[is.na(spillovermatrix)] <- 0  
plotspilloverplot <- function(x, y) {
  name_x <- names(x)
  name_y <- names(y)
  dat <- data.frame(x = unname(x), y = unname(y))
  return(ggplot(dat) + geom_bin2d(aes(x, y, fill = ..density..), bins = params$DENSITYSQUARES, show.legend = FALSE) + scale_fill_gradientn(colours = colorRamps::matlab.like2(100))  + labs(title = paste(marker, "-", metalmarkers[[marker]], "x", spillovermarker, "-", metalmarkers[[spillovermarker]]), x = name_x, y = name_y) + theme(text = element_text(size=5), axis.text.x = element_text(size=5, hjust=1), axis.text.y = element_text(size=5, hjust=1)))}

## Main Output Loop
for (marker in lineage_channels) {
<<<<<<< HEAD
  cat("## ", paste(marker, "-", metalmarkers[[marker]], "\n"))
  message("Generating Plots and Tables for Marker ", marker, " (", which(marker == lineage_channels), " out of ", length(lineage_channels), ").")
=======
  message("Generating Plots and Tables for Marker ", marker, " (", which(marker == lineage_channels), " out of ", length(lineage_channels), ").")
  cat("## ", paste(marker, "-", metalmarkers[[marker]], "\n"))
>>>>>>> eb6a6a4d6835886af27d79d4c842f42c10259c3d
  
  ## Check if Spillover needed
  if (params$SPILLOVER != "Do Nothing") {
    if (!(marker %in% spillovermarkers))  {
      cat("\n- Marker", marker, "was not found in Spillover Matrix. Not checking, scoring or compensating for spillover.", sep = " ")
<<<<<<< HEAD
    } else {
      
=======
      } else {
    
>>>>>>> eb6a6a4d6835886af27d79d4c842f42c10259c3d
      ## Set up Table with Relevant Spillover Matrix Information
      spillovercontributing <- as.data.frame(t(compensationmatrix[marker, ])) 
      colnames(spillovercontributing) <- "Percentage Contributing"
      spilloverreceiving <- data.frame("Percentage Receiving" = compensationmatrix[, marker], row.names = colnames(compensationmatrix))
      spilloversummary <- data.frame(spillovercontributing, spilloverreceiving)
      spilloversummary <- spilloversummary[!(apply(spilloversummary, 1, function(x) all(is.na(x)))),]
      spilloversummary[is.na(spilloversummary)] <- 0
      spilloversummary$Ratio.of.max.Contributing <- NA
      spilloversummary$Ratio.of.max.Receiving <- NA
<<<<<<< HEAD
      
      ## Spillover Scoring
      spillover_worst_contributor_score <- 0
      spillover_worst_receiver_score <- 0
      spillover_worst_contributor <- NA
      spillover_worst_receiver <- NA
      current_rows <- fcs@exprs[,"FileNum"] == bestsamples[marker]
      uncomp_maxcurrentexpression <- quantile(fcs@exprs[current_rows,marker], 0.98)
      if (uncomp_maxcurrentexpression == 0) {uncomp_maxcurrentexpression <- quantile(fcs@exprs[current_rows,marker], 0.995)}
      
=======
      
      ## Spillover Scoring
      spillover_worst_contributor_score <- 0
      spillover_worst_receiver_score <- 0
      spillover_worst_contributor <- NA
      spillover_worst_receiver <- NA
      current_rows <- fcs@exprs[,"FileNum"] == bestsamples[marker]
      uncomp_maxcurrentexpression <- quantile(fcs@exprs[current_rows,marker], 0.98)
      if (uncomp_maxcurrentexpression == 0) {uncomp_maxcurrentexpression <- quantile(fcs@exprs[current_rows,marker], 0.995)}
      
>>>>>>> eb6a6a4d6835886af27d79d4c842f42c10259c3d
      ## For each Spillover Marker
      for (spillovermarker in spillovermarkers) {try({
        if (((spillovermatrix[marker,spillovermarker] > 0) | (spillovermatrix[spillovermarker,marker] > 0)) & (spillovermarker != marker)) {
          spillovermarker_rows <- fcs@exprs[,"FileNum"] == bestsamples[spillovermarker]
          uncomp_maxspilloverexpression <- quantile(fcs@exprs[spillovermarker_rows,spillovermarker], 0.98)
          if (uncomp_maxspilloverexpression == 0) {uncomp_maxspilloverexpression <- quantile(fcs@exprs[spillovermarker_rows,spillovermarker], 0.995)}
          
          ## Score Contributing Spillover          
          spilloverpercentage <- spillovermatrix[marker,spillovermarker]
          spillovermarkerscore <- (uncomp_maxcurrentexpression*(spilloverpercentage/100))/uncomp_maxspilloverexpression
          spilloversummary[spillovermarker,"Ratio.of.max.Contributing"] <- round(spillovermarkerscore, 2)
          spillover_worst_contributor_score <- max(spillover_worst_contributor_score, round(spillovermarkerscore, 2))
<<<<<<< HEAD
          if (spillover_worst_contributor_score == round(spillovermarkerscore,2)) {spillover_worst_contributor <- spillovermarker}
=======
          if (spillover_worst_contributor_score == spillovermarkerscore) {spillover_worst_contributor <- spillovermarker}
>>>>>>> eb6a6a4d6835886af27d79d4c842f42c10259c3d
          
          ## Score Receiving Spillover
          spilloverpercentage <- spillovermatrix[spillovermarker,marker]
          spillovermarkerscore <- (uncomp_maxspilloverexpression*(spilloverpercentage/100))/uncomp_maxcurrentexpression
          spilloversummary[spillovermarker,"Ratio.of.max.Receiving"] <- round(spillovermarkerscore, 2)
          spillover_worst_receiver_score <- max(spillover_worst_receiver_score, round(spillovermarkerscore, 2))
<<<<<<< HEAD
          if (spillover_worst_receiver_score == round(spillovermarkerscore,2)) {spillover_worst_receiver <- spillovermarker}
          
          
          ## Generate Spillover Plot between two markers
          spilloverplots[[marker]][[spillovermarker]] <- plotspilloverplot(x = exprs[marker], y = exprs[spillovermarker])
        }
      })}
      
      ## Print Spillover Summary for this Marker
      spilloversummaries[[marker]] <- spilloversummary
      spilloversummary <- knitr::kable(spilloversummary, caption = "Table showing the spillover percentages and ratios both to and from other channels")
      spilloversummary <- kable_styling(spilloversummary, bootstrap_options = c("striped", "hover", "responsive"), full_width = FALSE)
      print(spilloversummary)
      cat("Marker Contributing Worst Spillover Relative to this marker:", spillover_worst_contributor, "with ratio of", spillover_worst_contributor_score, "  \n")
      cat("\n")
      cat("Marker Receiving Relative Worst Spillover from this marker:", spillover_worst_receiver, "with ratio of", spillover_worst_receiver_score, "  \n")
      
      ## Print Spillover Plots for this Marker
      if (!(is.null(spilloverplots[[marker]]))) {
        finalspilloverplots[[marker]] <- do.call("grid.arrange", c(spilloverplots[[marker]], ncol = ceiling(sqrt(length(spilloverplots[[marker]])))))
        
        ## Save Marker-Specific Spillover Plots and Spillover Summary Tables as output files
        spilloverplot_filename <- paste("Spillover Plots for Marker ", marker, " - ", metalmarkers[[marker]], ".png", sep = "")
        suppressMessages(ggsave(plot = finalspilloverplots[[marker]], filename = spilloverplot_filename))
      }
=======
          if (spillover_worst_receiver_score == spillovermarkerscore) {spillover_worst_receiver <- spillovermarker}
           
          
          ## Generate Spillover Plot between two markers
          spilloverplots[[marker]][[spillovermarker]] <- plotspilloverplot(x = exprs[marker], y = exprs[spillovermarker])
        }
      })}
      
      ## Print Spillover Summary for this Marker
      spilloversummaries[[marker]] <- spilloversummary
      spilloversummary <- knitr::kable(spilloversummary, caption = "Table showing the spillover percentages and ratios both to and from other channels")
      spilloversummary <- kable_styling(spilloversummary, bootstrap_options = c("striped", "hover", "responsive"), full_width = FALSE)
      print(spilloversummary)
      cat("Marker Contributing Worst Spillover Relative to this marker:", spillover_worst_contributor, "with ratio of", spillover_worst_contributor_score)
      cat("\n")
      cat("Marker Receiving Relative Worst Spillover from this marker:", spillover_worst_receiver, "with ratio of", spillover_worst_receiver_score)
      
      ## Print Spillover Plots for this Marker
      if (!(is.null(spilloverplots[[marker]]))) {
        finalspilloverplots[[marker]] <- do.call("grid.arrange", c(spilloverplots[[marker]], ncol = ceiling(sqrt(length(spilloverplots[[marker]])))))

        ## Save Marker-Specific Spillover Plots and Spillover Summary Tables as output files
        spilloverplot_filename <- paste("Spillover Plots for Marker ", marker, " - ", metalmarkers[[marker]], ".png", sep = "")
        suppressMessages(ggsave(plot = finalspilloverplots[[marker]], filename = spilloverplot_filename))
        }
>>>>>>> eb6a6a4d6835886af27d79d4c842f42c10259c3d
      spilloversummarytable_filename <- paste("Spillover Summary for Marker ", marker, " - ", metalmarkers[[marker]], ".tsv", sep = "")
      write.table(spilloversummaries[[marker]], sep = "\t", col.names = TRUE, file = spilloversummarytable_filename)
    }
  }
  
  ## Print Base Score Table for this Marker
  tkable <- knitr::kable(x = t(as.data.frame(scores[[marker]])), caption = "Table Showing all base scores for this Marker, for each Concentration.")
  tkable <- kable_styling(tkable , bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = FALSE)
  print(tkable)
  
  ## Print Density Plot for this Marker
  cat("\n- The Following Graph shows the intensity of each Concentration. Red box = Highest Overall Score.")
  if ((params$SPILLOVER == "Give Warnings & Compensate Data") & (marker %in% spillovermarkers)) 
  {cat("\n- This Graph has been compensated for Spillover effects.")} 
  else {cat("\n- This Graph has NOT been compensated for any Spillover effects.")}
  print(densityplots[[marker]])
  
  ## Save Marker-Specific Plots and Score Table as output files
  densityplot_filename <- paste("Expression for Marker ", marker, " - ", metalmarkers[[marker]], ".png", sep = "")
  suppressMessages(ggsave(plot = densityplots[[marker]], filename = densityplot_filename))
  scoretable_filename <- paste("Scores for Marker ", marker, " - ", metalmarkers[[marker]], ".tsv", sep = "")
  write.table(t(as.data.frame(scores[[marker]])), sep = "\t", col.names = TRUE, file = scoretable_filename)
}
<<<<<<< HEAD

message("\n\nFinishing up by Exporting R Workspace and Finalizing Report...")
=======
>>>>>>> eb6a6a4d6835886af27d79d4c842f42c10259c3d

## Write Summary Table
setwd(outputdir)
write.table(t(as.data.frame(bestsamples)), sep = "\t", file = "Optimal Marker Concentrations Summary.tsv", col.names = FALSE)

## Write R Workspace for future analysis
save.image(file = "R Workspace.Rdata")

```
